config/routes.rb
MusicApp::Application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
  	resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do
  	resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index]

  root 'static_pages#index'
end

app/models/album.rb
class Album < ActiveRecord::Base
	validates :name, :band, :live_recording, presence: true

	belongs_to :band
	has_many :tracks

end

app/models/band.rb
class Band < ActiveRecord::Base
	validates :name, presence: true
	
	has_many :albums
	has_many :tracks, through: :albums, source: :tracks
end

app/models/track.rb
class Track < ActiveRecord::Base
	validates :name, :album, :band, :bonus, presence: true

	belongs_to :album
	has_one :band, through: :album, source: :band
end

app/models/user.rb
class User < ActiveRecord::Base

    #this is just for the validation, not persistent.
	attr_reader :password

	validates :email, :session_token, presence: true
	validates :email, uniqueness: true
	validates :password_digest, presence: { message: "Password can't be blank"}
	validates :password, length: { minimum: 6, allow_nil: true }
	after_initialize :ensure_session_token

	def self.generate_session_token
		SecureRandom::urlsafe_base64(16)
	end

	def reset_session_token!
		self.session_token = self.class.generate_session_token
		self.save!
		self.session_token
	end

	def password=(password)
		@password = password
		self.password_digest = BCrypt::Password.create(password)
	end

	def is_password?(password)
		BCrypt::Password.new(self.password_digest).is_password?(password)
	end

	def self.find_by_credentials(email, password)
		user = User.find_by(email: email)
		user.try(:is_password?, password) ? user : nil 
	end

	private

	def ensure_session_token
		self.session_token ||= self.class.generate_session_token
	end


end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def create
    album = Album.new(album_params)
    if album.save
      redirect_to bands_url
    else
      flash.now[:errors] = album.errors.full_messages
      render :new
    end
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

  private
  def album_params
    params.require(:album).permit(:name, :band_id, :live_recording)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?

  def current_user
  	return nil if session[:session_token].nil?
  	@current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
  	!!current_user
  end

  def login!(user)
  	@current_user = user
  	session[:session_token] = user.session_token
  	#Session.create(session_token: session[:session_token], user_id: user.id)
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_current_band, only: [:edit, :show, :update, :destroy]

  def index
    @bands = Band.all
  end

  def create
    band = Band.new(band_params)
    if band.save
      redirect_to bands_url
    else
      flash.now[:errors] = band.errors.full_messages
      render :new
    end
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
    @band.update(band_params)
    if @band.save
      redirect to bands_url
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end  
  end

  def destroy
    @band.try(:destroy)
    redirect_to bands_url
  end

  private

  def set_current_band
    @band = Band.find(params[:id])
  end

  def band_params
    params.require(:band).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.find_by_credentials(params[:user][:email],
                                    params[:user][:password])
    if user.nil?
      flash.now[:errors] ||= []
      flash.now[:errors] << "Bad Email/Password combination"
      render :new
    else
      login!(user)
      redirect_to user_url(user.id)
    end
  end

  def destroy
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
    redirect_to new_session_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
	end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
	def create
	end

	def new
	end

	def edit
	end

	def show
	end

	def update
	end

	def destroy
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  end
  
  def create
    user = User.new(user_params)
    if user.save
      login!(user)
      redirect_to user_url(user.id)
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
  
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    html = '<input type="hidden"'
    html +=       'name="authenticity_token"'
    html +=       'value="<%= form_authenticity_token %>">'

    html.html_safe
  end

  def name_form_entry(type)
    html = "<label for=\"#{type}_name\">#{type.to_s.capitalize} "
    html += "Name</label>"
    html += "<input id=\"#{type}_name\""
    html +=      "name=\"#{type}[name]\""
    html +=      'type="text">'

    html.html_safe
  end


  def dropdown(type)
    child = (type == "band" ? "album" : "track")
    id_sym = "#{type.to_s}_id".to_sym
    


    html = "<label for=\"#{type}_id\">#{type.to_s.capitalize} Name</label>"
    html +="<select name=\"#{child}[#{type}_id]\" value=\"<%= :#{type}_id %>\">"
    type.capitalize.constantize.all.each do |item|
      html +="<option value=\"#{item.id}\""
      html += "selected" if id_sym == item.id
      html += ">"
      html += item.name
      html +="</option>"
    end
    html +="</select>"

    html.html_safe
  end

  def submit(type)
    "<input type=\"submit\" value=\"Click to submit #{type}\">".html_safe
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/new.html.erb
<h2>Enter New Album</h2>

<form action="<%= albums_url %>" method="post">
<%= auth_token %>
<%= name_form_entry("album") %>
<br>
<%= dropdown("band") %>
<br>
<label>Recording</label>
  <input name="album[live_recording]"
         id="live"
         type="radio"
         value= true>
    <lable for="live">Live</lable>
  <input name="album[live_recording]"
         id="studio"
         type="radio"
         value= false>
    <label for="studio">Studio</label>
<br>
<%= submit("album") %>
</form>

app/views/bands/index.html.erb
<% if @bands %>
  <% @bands.each do |band| %>
    <%= band.name %>
  <% end %>
<% end %>

app/views/bands/new.html.erb
<h2>Enter New Band</h2>

<form action="<%= bands_url %>" method="post">
<%= auth_token %>
<%= name_form_entry("band") %>
<br>
<%= submit %>
</form>

app/views/layouts/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

app/views/layouts/_signform.html.erb
<%= auth_token %>

<label for="user_email">Email</label>
<input id="user_email"
       name="user[email]"
       type="text">
<br>
<label for="user_pass">Password</label>
<input id="user_pass"
       name="user[password]"
       type="password">
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/errors' %>
<%= render flash[:welcome] if flash[:welcome] %>
<% if logged_in? %>
  <%= button_to "Log out", session_url, method: :delete %>
<% end %> 

<%= yield %>

</body>
</html>

app/views/tracks/new.html.erb
<h2>Enter New Track</h2>

<form action="<%= tracks_url %>" method="post">
<%= auth_token %>
<%= name_form_entry("track") %>
<br>
<%= dropdown("album") %>
<br>
<label>Track Type</label>
  <input name="track[bonus]"
         id="regular"
         type="radio"
         value= false>
    <lable for="regular">Regular</lable>
  <input name="track[bonus]"
         id="bonus"
         type="radio"
         value= true>
    <label for="bonus">Bonus</label>
<br>
<label for="lyrics">Lyrics</label>
<textarea name="track[lyrics]"
          id="lyrics"
          value="<%= @track.try(:lyrics) %>">
</textarea>
<br>
<%= submit("album") %>
</form>

app/views/users/new.html.erb
<h2>Sign up</h2>

<form action="<%= users_url %>" method="post">
  <%= render 'layouts/signform' %>
  <input type="submit" value="Click here to sign up!">
</form>

app/views/users/show.html.erb
<%= current_user.email %>